version: 2.1

orbs:
  terraform: circleci/terraform@3.1.0
  python: circleci/python@2.0.3
  gcp-gcr: circleci/gcp-gcr@0.15.0

workflows:
  deploy_infrastructure:
    jobs:
      - terraform/fmt:
          checkout: true
          context: terraform
      - terraform/validate:
          checkout: true
          context: terraform
          requires:
            - terraform/fmt
      - terraform/plan:
          checkout: true
          context: terraform
          persist-workspace: true
          requires:
            - terraform/validate
      - request-deploy:
          type: approval
          requires:
            - terraform/plan
      - terraform/apply:
          attach-workspace: true
          context: terraform
          requires:
            - request-deploy

  code-validation:
    jobs:
      - python-test

jobs:
  python-test:
    docker:
      - image: circleci/python:3.9.1
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: pip install -r cloud_function/requirements.txt && pip install ./cloud_function
      - run:
          name: Run tests
          command: export PYTHONPATH=$PYTHONPATH:/cloud_function && ./cloud_function/test.sh

  build-and-push:
    executor: gcp-gcr/default
    steps:
      - checkout
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
          image: orb-test
          no_output_timeout: 20m
          registry-url: eu.gcr.io
      - gcp-gcr/push-image:
          digest-path: /tmp/digest.txt
          image: orb-test
          registry-url: eu.gcr.io
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

  # deploy:
  #   docker:
  #     - image: google/cloud-sdk
  #   steps:
  #     - checkout
  #     - run: |
  #         echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
  #         gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
  #         gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
  #         gcloud functions deploy twitter-scraper --region ${GOOGLE_COMPUTE_ZONE} --entry-point handler --runtime python39 --memory 512 --trigger-http --timeout 540 --set-env-vars RUNTIME=cloud,DB_NAME=twitter,DB_USER=postgres,GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID} --verbosity=debug
